const express = require('express')
const app = express()
app.use(express.json())
const quotes = require('./models/schema')
const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost:27017/quoteDb')
.then(() => console.log('Connected to MongoDB'))
.catch(err => console.error('Could not connect to MongoDB', err))
app.listen(3000, () => console.log('Server running on port 3000'))